pulsecare:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dev.duckdb'
      schema: raw
      threads: 4

    prod:
      type: duckdb
      path: 'prod.duckdb'
      schema: raw
      threads: 4
